naming:
  FunctionNaming:
    active: true
    excludes: ['**/test/**', '**/androidTest/**']
    functionPattern: '[a-z][a-zA-Z0-9]*'
    excludeClassPattern: '$^'
    ignoreAnnotated:
      - 'Composable'
